import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './contexts/**/*.{js,ts,jsx,tsx}',
    './lib/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: '#e5e5e5',
        background: '#ffffff',
        foreground: '#0a0a0a',
        muted: {
          DEFAULT: '#6b7280',
          foreground: '#9ca3af',
        },
        primary: {
          50: '#fafafa',
          100: '#f4f4f5',
          200: '#e4e4e7',
          300: '#d4d4d8',
          400: '#a1a1aa',
          500: '#52525b',
          600: '#18181b',
          700: '#09090b',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
        },
        success: {
          50: '#f0fdf4',
          500: '#16a34a',
          600: '#15803d',
        },
        warning: {
          50: '#fffbeb',
          500: '#f59e0b',
          600: '#d97706',
        },
        accent: {
          purple: '#8b5cf6',
          pink: '#ec4899',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
      },
      fontSize: {
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['32px', { lineHeight: '40px' }],
        '4xl': ['48px', { lineHeight: '56px' }],
        '5xl': ['64px', { lineHeight: '72px' }],
      },
      borderRadius: {
        'pill': '9999px',
        DEFAULT: '8px',
      },
      boxShadow: {
        xs: '0 1px 3px rgba(0, 0, 0, 0.04)',
        card: '0 1px 6px rgba(0, 0, 0, 0.06)',
        'card-hover': '0 4px 20px rgba(0, 0, 0, 0.06)',
        dropdown: '0 12px 40px rgba(0, 0, 0, 0.1)',
        modal: '0 20px 60px rgba(0, 0, 0, 0.15)',
        panel: '-8px 0 40px rgba(0, 0, 0, 0.08)',
      },
      zIndex: {
        dropdown: '10',
        sticky: '20',
        overlay: '40',
        modal: '50',
        toast: '60',
        tooltip: '70',
      },
      animation: {
        'reveal-fade-up': 'reveal-fade-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'reveal-fade-down': 'reveal-fade-down 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'reveal-fade-left': 'reveal-fade-left 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'reveal-fade-right': 'reveal-fade-right 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'reveal-scale': 'reveal-scale 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'reveal-flip': 'reveal-flip 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'matrix-rain': 'matrix-rain 15s linear infinite',
        'mesh-gradient': 'mesh-gradient 20s ease-in-out infinite',
        'noise': 'noise 3s steps(1) infinite',
        'particle-float': 'particle-float 20s ease-in-out infinite',
        'shimmer': 'shimmer 3s linear infinite',
        'holographic': 'holographic 5s linear infinite',
        'scanline': 'scanline 4s linear infinite',
        'pulsing-ring': 'pulsing-ring 2s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'counter': 'counter 1.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'progress-fill': 'progress-fill 1.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'line-draw': 'line-draw 1s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'bounce-entrance': 'bounce-entrance 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'card-flip': 'card-flip 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'spin-entrance': 'spin-entrance 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'ripple': 'ripple 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'gradient-text': 'gradient-text 8s ease-in-out infinite',
        'nav-slide-down': 'nav-slide-down 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'typewriter': 'typewriter 2s steps(40) forwards',
        'flowing-light': 'flowing-light 3s linear infinite',
      },
      transitionDuration: {
        'xs': '150ms',
        'sm': '300ms',
        'md': '600ms',
        'lg': '800ms',
        'xl': '1200ms',
      },
      transitionTimingFunction: {
        'ease-out-quart': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'ease-in-out-cubic': 'cubic-bezier(0.65, 0, 0.35, 1)',
        'ease-out-back': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')({ strategy: 'class' })],
};

export default config;
